import localFont from "next/font/local";
import "./globals.css";

import { Poppins } from '@next/font/google';

const poppins = Poppins({
  weight: ['400', '700'],  // Kamu bisa menyesuaikan weight yang dibutuhkan
  subsets: ['latin'],
});

export const metadata = {
  title: "Sekolah Crypto Indonesia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={poppins.className}
      >
        {children}
      </body>
    </html>
  );
}
